"""Python Script Template."""

from typing import Any, Dict, List, Optional, Tuple

import gym.error
import numpy as np

from .adversarial_wrapper import AdversarialWrapper

try:
    from gym.envs.mujoco import MujocoEnv
    class MujocoAdversarialWrapper(AdversarialWrapper):
        """Wrapper for Mujoco adversarial environments."""

        def __init__(
            self,
            env: MujocoEnv,
            alpha: float = ...,
            force_body_names: Optional[List[str]] = ...,
            new_mass: Optional[Dict[str, float]] = ...,
            new_friction: Optional[Dict[str, float]] = ...,
        ) -> None: ...
        def _antagonist_action_to_xfrc(self, antagonist_action: np.ndarray) -> None: ...
        def adversarial_step(
            self, protagonist_action: np.ndarray, antagonist_action: np.ndarray
        ) -> Tuple[np.ndarray, float, bool, dict]: ...
    def get_ant_torso_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_half_cheetah_torso_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_hopper_torso_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_humanoid_torso_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_humanoid_standup_torso_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_inverted_pendulum_pole_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_inverted_double_pendulum_pole2_env(
        **kwargs: Any,
    ) -> MujocoAdversarialWrapper: ...
    def get_walker_torso_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_reacher_body1_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_swimmer_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_pusher_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_thrower_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_stricker_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_half_cheetah_heel_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...
    def get_half_cheetah_torso_heel_env(**kwargs: Any) -> MujocoAdversarialWrapper: ...

except (ModuleNotFoundError, gym.error.DependencyNotInstalled):
    pass
